import React, { useEffect, useState } from 'react';               import {
  SimpleGrid,                                                       Box,                                                              Stat,                                                             StatLabel,
  StatNumber,                                                       StatHelpText,                                                     StatArrow,                                                        useColorModeValue,
  Icon,                                                             Flex                                                            } from '@chakra-ui/react';
import { FaBus, FaTicketAlt, FaUsers, FaMoneyBillWave } from 'react-icons/fa';                                                      import { collection, getDocs, query } from 'firebase/firestore';  import { db } from "../firebase/config";
                                                                  const DashboardStats = () => {                                      const [stats, setStats] = useState({                                ticketsVendidos: 0,
    vehiculosActivos: 0,                                              usuariosRegistrados: 0,                                           ingresosTotales: 0                                              });
  const [loading, setLoading] = useState(true);                                                                                       useEffect(() => {                                                   const fetchData = async () => {
      try {                                                               const ventasQuery = query(collection(db, "ventas"));              const ventasSnapshot = await getDocs(ventasQuery);                const ventas = ventasSnapshot.docs.map((doc) => doc.data());                                                                                                                                          const vehiculosQuery = query(collection(db, "vehiculos"));        const vehiculosSnapshot = await getDocs(vehiculosQuery);
        const vehiculos = vehiculosSnapshot.docs.map((doc) => doc.data());                                                                                                                                    const usuariosQuery = query(collection(db, "usuarios"));
        const usuariosSnapshot = await getDocs(usuariosQuery);            const usuarios = usuariosSnapshot.docs.map((doc) => doc.data());                                                            
        const ticketsVendidos = ventas.length;                            const vehiculosActivos = vehiculos.length;                        const usuariosRegistrados = usuarios.length;                      const ingresosTotales = ventas.reduce((sum, venta) => sum + (venta.monto || 0), 0);                                                                                                                   setStats({                                                          ticketsVendidos,
          vehiculosActivos,                                                 usuariosRegistrados,                                              ingresosTotales                                                 });
      } catch (error) {                                                   console.error("Error fetching data: ", error);                  } finally {
        setLoading(false);                                              }                                                               };
                                                                      fetchData();                                                    }, []);
                                                                    const bgColor = useColorModeValue('white', 'gray.700');           const borderColor = useColorModeValue('gray.200', 'gray.600');
                                                                    const statCards = [                                                 {                                                                   label: 'Tickets Vendidos',
      value: stats.ticketsVendidos,                                     icon: FaTicketAlt,                                                percentage: 23,                                                   increase: true
    },                                                                {                                                                   label: 'Vehículos Activos',                                       value: stats.vehiculosActivos,
      icon: FaBus,                                                      percentage: 5,                                                    increase: true                                                  },
    {                                                                   label: 'Usuarios Registrados',                                    value: stats.usuariosRegistrados,                                 icon: FaUsers,
      percentage: 12,                                                   increase: true                                                  },                                                                {
      label: 'Ingresos Totales',                                        value: `S/ ${stats.ingresosTotales.toFixed(2)}`,                  icon: FaMoneyBillWave,                                            percentage: 15,
      increase: true                                                  }                                                               ];                                                              
  return (                                                            <SimpleGrid columns={{ base: 1, md: 2, lg: 4 }} spacing={5}>        {statCards.map((stat, index) => (                                   <Box
          key={index}                                                       p={5}                                                             bg={bgColor}
          borderRadius="lg"                                                 borderWidth="1px"                                                 borderColor={borderColor}                                         shadow="sm"
        >                                                                   <Stat>                                                              <Flex alignItems="center" justifyContent="space-between">
              <Box>                                                               <StatLabel color="gray.500">{stat.label}</StatLabel>                                                                                <StatNumber fontSize="2xl" fontWeight="bold">
                  {loading ? 'Cargando...' : stat.value}                          </StatNumber>                                                   </Box>                                                            <Icon as={stat.icon} w={8} h={8} color="blue.500" />
            </Flex>                                                           <StatHelpText>                                                      <StatArrow type={stat.increase ? 'increase' : 'decrease'} />
              {stat.percentage}%                                              </StatHelpText>                                                 </Stat>                                                         </Box>
      ))}                                                             </SimpleGrid>                                                   );                                                              };
                                                                  export default DashboardStats;
