import React from 'react';
import {                                                            Box,                                                              Grid,                                                             GridItem,
  Stat,                                                             StatLabel,                                                        StatNumber,                                                       StatHelpText,
  Icon,                                                             useColorModeValue,                                              } from '@chakra-ui/react';
import { FaBus, FaTicketAlt, FaBox, FaRoute } from 'react-icons/fa';                                                                import { collection, getDocs } from 'firebase/firestore';         import { db } from '../../firebase/config';
                                                                  const DashboardCard = ({ title, value, icon, helpText, bgColor }) => (                                                                <Box
    p={5}                                                             bg={bgColor}                                                      borderRadius="lg"                                                 boxShadow="sm"
    transition="all 0.3s"                                             _hover={{ transform: 'translateY(-2px)', boxShadow: 'md' }}     >                                                                   <Grid templateColumns="3fr 1fr" gap={4}>
      <GridItem>                                                          <Stat>                                                              <StatLabel fontSize="lg" color={useColorModeValue('gray.600', 'gray.300')}>
            {title}                                                         </StatLabel>                                                      <StatNumber fontSize="2xl" fontWeight="bold">                       {value}
          </StatNumber>                                                     <StatHelpText>{helpText}</StatHelpText>                         </Stat>                                                         </GridItem>
      <GridItem display="flex" alignItems="center" justifyContent="center">                                                                 <Icon as={icon} w={10} h={10} color={useColorModeValue('blue.500', 'blue.300')} />
      </GridItem>                                                     </Grid>                                                         </Box>                                                          );
                                                                  const Dashboard = () => {                                           const [stats, setStats] = React.useState({                          vehiculos: 0,
    tickets: 0,                                                       encomiendas: 0,                                                   rutas: 0,                                                       });
                                                                    const bgColor = useColorModeValue('white', 'gray.700');                                                                             React.useEffect(() => {
    const fetchStats = async () => {                                    try {                                                               // Obtener estadísticas de vehículos                              const vehiculosQuery = collection(db, 'vehiculos');
        const vehiculosSnap = await getDocs(vehiculosQuery);                                                                                // Obtener estadísticas de tickets                                const ticketsQuery = collection(db, 'tickets');
        const ticketsSnap = await getDocs(ticketsQuery);                                                                                    // Obtener estadísticas de encomiendas                            const encomiendasQuery = collection(db, 'encomiendas');
        const encomiendasSnap = await getDocs(encomiendasQuery);                                                                            // Obtener estadísticas de rutas                                  const rutasQuery = collection(db, 'rutas');
        const rutasSnap = await getDocs(rutasQuery);                                                                                        setStats({                                                          vehiculos: vehiculosSnap.size,
          tickets: ticketsSnap.size,                                        encomiendas: encomiendasSnap.size,                                rutas: rutasSnap.size,                                          });
      } catch (error) {                                                   console.error('Error al obtener estadísticas:', error);         }                                                               };
                                                                      fetchStats();                                                   }, []);                                                         
  return (                                                            <Grid                                                               templateColumns={{ base: '1fr', md: 'repeat(2, 1fr)', lg: 'repeat(4, 1fr)' }}                                                       gap={6}                                                           p={4}                                                           >
      <DashboardCard                                                      title="Vehículos"                                                 value={stats.vehiculos}                                           icon={FaBus}
        helpText="Total de vehículos registrados"                         bgColor={bgColor}                                               />                                                                <DashboardCard
        title="Tickets"                                                   value={stats.tickets}                                             icon={FaTicketAlt}                                                helpText="Tickets vendidos hoy"
        bgColor={bgColor}                                               />                                                                <DashboardCard                                                      title="Encomiendas"
        value={stats.encomiendas}                                         icon={FaBox}                                                      helpText="Encomiendas registradas"                                bgColor={bgColor}
      />                                                                <DashboardCard                                                      title="Rutas"                                                     value={stats.rutas}
        icon={FaRoute}                                                    helpText="Rutas activas"                                          bgColor={bgColor}                                               />
    </Grid>                                                         );                                                              };                                                                
export default Dashboard;
