import React from 'react';
import {                                                            SimpleGrid,                                                       Box,                                                              useColorModeValue,
  Heading,                                                        } from '@chakra-ui/react';                                        import {                                                            LineChart,
  Line,                                                             XAxis,                                                            YAxis,                                                            CartesianGrid,
  Tooltip,                                                          Legend,                                                           ResponsiveContainer,
  BarChart,                                                         Bar                                                             } from 'recharts';                                                
const DashboardCharts = ({ ventasData, ticketsData }) => {          const bgColor = useColorModeValue('white', 'gray.700');           const borderColor = useColorModeValue('gray.200', 'gray.600');    const textColor = useColorModeValue('gray.800', 'white');
                                                                    return (                                                            <SimpleGrid columns={{ base: 1, lg: 2 }} spacing={5} mt={5}>        <Box
        p={5}                                                             bg={bgColor}                                                      borderRadius="lg"                                                 borderWidth="1px"
        borderColor={borderColor}                                         shadow="sm"                                                     >                                                                   <Heading size="md" mb={4} color={textColor}>
          Ventas por Mes                                                  </Heading>                                                        <ResponsiveContainer width="100%" height={300}>                     <LineChart
            data={ventasData}                                                 margin={{                                                           top: 5,                                                           right: 30,
              left: 20,                                                         bottom: 5,                                                      }}                                                              >
            <CartesianGrid strokeDasharray="3 3" />                           <XAxis dataKey="name" />                                          <YAxis />                                                         <Tooltip />
            <Legend />                                                        <Line                                                               type="monotone"                                                   dataKey="ventas"
              stroke="#3182ce"                                                  activeDot={{ r: 8 }}                                            />                                                              </LineChart>
        </ResponsiveContainer>                                          </Box>                                                                                                                              <Box
        p={5}                                                             bg={bgColor}                                                      borderRadius="lg"                                                 borderWidth="1px"
        borderColor={borderColor}                                         shadow="sm"                                                     >                                                                   <Heading size="md" mb={4} color={textColor}>
          Tickets Vendidos por Día                                        </Heading>                                                        <ResponsiveContainer width="100%" height={300}>                     <BarChart
            data={ticketsData}                                                margin={{                                                           top: 5,                                                           right: 30,
              left: 20,                                                         bottom: 5,                                                      }}
          >                                                                   <CartesianGrid strokeDasharray="3 3" />                           <XAxis dataKey="name" />                                          <YAxis />
            <Tooltip />                                                       <Legend />                                                        <Bar dataKey="tickets" fill="#4299e1" />                        </BarChart>
        </ResponsiveContainer>                                          </Box>                                                          </SimpleGrid>                                                   );
};                                                                                                                                  export default DashboardCharts;
